import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mlh
 */
public class Connexion extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Pseudo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Mdp = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templateconnexion.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templateconnexion.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templateconnexion.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Adresse mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 190, 170, 26));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("©Louis Henri Merwane ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 210, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 190, 50));

        Pseudo.setBackground(new java.awt.Color(0, 153, 204));
        Pseudo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pseudo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 300, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Mot de Passe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        Mdp.setBackground(new java.awt.Color(0, 204, 204));
        Mdp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 300, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templateconnexion.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Connection con=null;
       ResultSet rs=null;
       PreparedStatement pst=null;
       //demande de rentrer tous les champs via des tests
       if (Pseudo.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Veuillez rentrer votre adresse mail");
           return;
        }
    
        if (Mdp.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Veuillez rentrer un mot de passe");
           return;
          
            }
        //connexion à la base de données
        con=ConnexionBDD.ConnectDB();
        //on vérifie que le pseudo et le mot de passe rentré sont bien dans la table de la base de données pour permettre la connexion
        String sq1= "select * from utilisateur where EMAIL= '" + Pseudo.getText() + "' and MDP ='" + Mdp.getText() + "' ";
        try{
            pst=con.prepareStatement(sq1);
            rs= pst.executeQuery();
            //Email=rs.getText(Pseudo);
            if (rs.next()){
            if(rs.getInt("Droit") ==1){
             this.hide();
             Main1 frm=new Main1();
             frm.setVisible(true);
           }
            if(rs.getInt("Droit") ==2){
             this.hide();
             Main2 frm=new Main2();
             frm.setVisible(true);
           }
            if(rs.getInt("Droit") ==3){
             this.hide();
             Main3 frm=new Main3();
             frm.setVisible(true);
           }
            if(rs.getInt("Droit") ==4){
             this.hide();
             Main4 frm=new Main4();
             frm.setVisible(true);
                        }
            }
           else{
              JOptionPane.showMessageDialog(null, "La connexion a échouée, veuillez ré-essayer !");
          }
        }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }

   
    
//public String Email="";

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Mdp;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
