/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/**
 *
 * @author mlh
 */
public class Enseignant extends javax.swing.JFrame {
    //déclarations de variables
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    PreparedStatement pst2=null;
    /**
     * Creates new form Enseignant
     */
    
    //méthode reset permettant de réinitialiser tous les champs du formulaire
    private void reset()
{
    
    Nom.setText("");
    Prenom.setText("");
    Mdp.setText("");
    Pseudo.setText("");
    
    
    Enregistrer.setEnabled(true);
    
    }
    public Enseignant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nom = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        Pseudo = new javax.swing.JTextField();
        Mdp = new javax.swing.JTextField();
        Enregistrer = new javax.swing.JButton();
        Réinitialiser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nom.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 180, -1));

        Prenom.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 180, -1));

        Pseudo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 180, -1));

        Mdp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 180, -1));

        Enregistrer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Enregistrer.setText("Enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 200, 60));

        Réinitialiser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Réinitialiser.setText("Réinitialiser");
        Réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RéinitialiserActionPerformed(evt);
            }
        });
        getContentPane().add(Réinitialiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 60));
        Réinitialiser.getAccessibleContext().setAccessibleName("New");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Mot de Passe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 180, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Pseudo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 140, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 140, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("Ajouter un Enseignant");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 420, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Nom");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bleu fond.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        try{
            //connexion à la base de données
            con=ConnexionBDD.ConnectDB();
            //test pour s'assurer que l'utilisateur rempli bien tous les champs
            if (Nom.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer un Nom","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (Prenom.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer un Prénom","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (Pseudo.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer un Pseudo","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Mdp.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer un Mot de Passe","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //préparation à la requête SQL
            Statement stmt;
            stmt= con.createStatement();
            
            
            String sql= "insert into Personne(ID,nom,prenom,type, pseudo, mdp)values('0','"+ Nom.getText() + "','"+ Prenom.getText() + "', 'enseignant','"+Pseudo.getText()+"', '"+Mdp.getText()+"')";
            //exécution de la requête
            pst=con.prepareStatement(sql);
            pst.execute();
            
            
            JOptionPane.showMessageDialog(this,"Enregistré avec succès","Enseignant",JOptionPane.INFORMATION_MESSAGE);
            Enregistrer.setEnabled(false);
            
            

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_EnregistrerActionPerformed

    private void RéinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RéinitialiserActionPerformed
        reset();  // TODO add your handling code here:
    }//GEN-LAST:event_RéinitialiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Enseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Enregistrer;
    public javax.swing.JTextField Mdp;
    public javax.swing.JTextField Nom;
    public javax.swing.JTextField Prenom;
    public javax.swing.JTextField Pseudo;
    public javax.swing.JButton Réinitialiser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}

