import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mlh
 */
public class ListeSeanceAnnulees extends javax.swing.JFrame {
    //déclaration de variables
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form RechercherEnseignant
     */
    public ListeSeanceAnnulees() {
        initComponents();
    }
    //méthode permettant de réinitialiser tous les champs du formulaire
    private void reset()
{
    
    Rechercher.setEnabled(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Rechercher = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Liste des séances annulées");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        Rechercher.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 180, 50));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 847, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bleu fond.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 760));

        jScrollPane4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTable4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8h30-10h00", null, null, null, null, null, null},
                {"10h15-11h45", null, null, null, null, null, null},
                {"12h00-13h30", null, null, null, null, null, null},
                {"13h45-15h15", null, null, null, null, null, null},
                {"15h30-17h00", null, null, null, null, null, null},
                {"17h15-18h45", null, null, null, null, null, null},
                {"19h00-20h30", null, null, null, null, null, null}
            },
            new String [] {
                "Emploi du temps ", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 847, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        try{
            //connexion à la base de données
            con=ConnexionBDD.ConnectDB();
            
            
            
            
            String sql= "select * from seance where ETAT=0";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if (rs.next()){
              ListeEleve frm = new ListeEleve();
               
                String sql1= "select SEMAINE, DATE, HEURE_DEBUT as 'DEBUT', HEURE_FIN as 'FIN',cours.NOM as 'COURS', type_cours.NOM as 'TYPE' from seance, cours, type_cours Where cours.ID=seance.ID_COURS AND type_cours.ID=seance.ID_TYPE ORDER BY SEMAINE,DATE,DEBUT";
                
                pst=con.prepareStatement(sql1);
    
                rs= pst.executeQuery();
                
                //affichage des données recherchées sur un enseignant dans un tableau
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                                
                
            pst=con.prepareStatement(sql1);

            pst.execute();
            
            }
            
               
          
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_RechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeSeanceAnnulees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeSeanceAnnulees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeSeanceAnnulees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeSeanceAnnulees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeSeanceAnnulees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Rechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
