import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mlh
 */
public class PlanningEnseignant extends javax.swing.JFrame {
    //déclaration de variables
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form RechercherEnseignant
     */
    public PlanningEnseignant() {
        initComponents();
    }
    //méthode permettant de réinitialiser tous les champs du formulaire
    private void reset()
{
    
    Nom.setText("");
    Prenom.setText("");
    Rechercher.setEnabled(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        Réinitialiser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Planning par enseignant");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Nom de l'Enseignant");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Prénom de l'Enseignant");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        Nom.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 140, -1));

        Prenom.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 140, -1));

        Rechercher.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });
        getContentPane().add(Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 180, 50));

        Réinitialiser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Réinitialiser.setText("Réinitialiser");
        Réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RéinitialiserActionPerformed(evt);
            }
        });
        getContentPane().add(Réinitialiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 180, 50));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8h30-10h00", null, null, null, null, null, null},
                {"10h15-11h45", null, null, null, null, null, null},
                {"12h00-13h30", null, null, null, null, null, null},
                {"13h45-15h15", null, null, null, null, null, null},
                {"15h30-17h00", null, null, null, null, null, null},
                {"17h15-18h45", null, null, null, null, null, null},
                {"19h00-20h30", null, null, null, null, null, null}
            },
            new String [] {
                "Emploi du temps ", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 847, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bleu fond.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 760));

        jScrollPane4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTable4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8h30-10h00", null, null, null, null, null, null},
                {"10h15-11h45", null, null, null, null, null, null},
                {"12h00-13h30", null, null, null, null, null, null},
                {"13h45-15h15", null, null, null, null, null, null},
                {"15h30-17h00", null, null, null, null, null, null},
                {"17h15-18h45", null, null, null, null, null, null},
                {"19h00-20h30", null, null, null, null, null, null}
            },
            new String [] {
                "Emploi du temps ", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 847, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        try{
            //connexion à la base de données
            con=ConnexionBDD.ConnectDB();
            //tests pour s'assurer que l'utilisateur rentre bien tous les champs demandés
            if (Nom.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer le nom de l'enseignant","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (Prenom.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer le prenom de l'enseignant","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            
            String sql= "select ID,DROIT from utilisateur where (NOM= '" + Nom.getText() + "' and PRENOM ='" + Prenom.getText() + "')";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if (rs.next()){
                if(rs.getInt("Droit") ==3){
              PlanningEleve frm = new PlanningEleve();
               
                String sql1= "Select SEMAINE as 'Semaine', DATE as 'Date', HEURE_DEBUT as 'Début', HEURE_FIN as 'Fin', type_cours.NOM as 'Type', cours.NOM as 'Nom',salle.NOM as 'Salle',site.NOM as 'Site' from seance,cours,type_cours, salle, site Where seance.ID IN (Select ID_SEANCE from seance_enseignants Where ID_ENSEIGNANT='"+rs.getString("ID")+"') AND cours.ID=seance.ID_COURS AND type_cours.ID=ID_TYPE AND salle.ID IN (Select ID_SALLE from seance_salles Where seance_salles.ID_SEANCE=seance.ID) AND site.ID=salle.ID_SITE  ORDER BY SEMAINE, DATE, HEURE_DEBUT";
               
                
                pst=con.prepareStatement(sql1);
    
                rs= pst.executeQuery();
                
                //affichage des données recherchées sur un enseignant dans un tableau
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                                
                
            pst=con.prepareStatement(sql1);

            pst.execute();
            
            
            }
                else{
                JOptionPane.showMessageDialog( this, "La personne recherchée n'est pas enseignante","Error", JOptionPane.ERROR_MESSAGE);
                Nom.setText("");
                Prenom.setText("");
            }}
            else{
                JOptionPane.showMessageDialog( this, "L'enseignant recherché n'existe pas","Error", JOptionPane.ERROR_MESSAGE);
                Nom.setText("");
                Prenom.setText("");
            }
          
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_RechercherActionPerformed

    private void RéinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RéinitialiserActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_RéinitialiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanningEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanningEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanningEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanningEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanningEnseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Réinitialiser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
