import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mlh
 */
public class SupprimerSeance extends javax.swing.JFrame {
    //déclaration de variables
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form SupprimerNote
     */
    public SupprimerSeance() {
        initComponents();
    }
    //méthode permettant de réinitialiser tous les champs du formulaire
    private void reset()
{
    
    Nom.setText("");
    Date.setText("");
    Heure.setText("");
    
    Supprimer.setEnabled(true);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        Supprimer = new javax.swing.JButton();
        Réinitialiser = new javax.swing.JButton();
        Date = new javax.swing.JFormattedTextField();
        Heure = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Supprimer une Séance");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Date de la séance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Nom de la séance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Heure de début de séance");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        Nom.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 140, 40));

        Supprimer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 170, 60));

        Réinitialiser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Réinitialiser.setText("Réinitialiser");
        Réinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RéinitialiserActionPerformed(evt);
            }
        });
        getContentPane().add(Réinitialiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 180, 60));

        Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-mm-dd"))));
        Date.setText("aaaa-mm-jj");
        Date.setToolTipText("");
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 140, 40));

        Heure.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        Heure.setText("HH:mm:ss");
        getContentPane().add(Heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 150, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bleu fond.jpg"))); // NOI18N
        jLabel7.setText("jLabel6");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        try{
            //connexion à la base de données
            con=ConnexionBDD.ConnectDB();
            //tests pour s'assurer que les champs sont tous rempli
            if (Nom.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer le nom du cours","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (Date.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer la date de la séance","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Heure.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Veuillez rentrer l'heure de la séance","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            //préparation à la requête SQL
            Statement stmt;
            stmt= con.createStatement();
            String sql1="Select seance.ID from seance,cours where seance.DATE = '" + Date.getText() + "' and seance.HEURE_DEBUT ='" + Heure.getText() + "' AND seance.ID_COURS = cours.ID IN (Select cours.ID from cours where cours.NOM='" + Nom.getText() + "') ";
            //exécution de la requête
            pst=con.prepareStatement(sql1);
            rs=stmt.executeQuery(sql1);
            while (rs.next()){
                SupprimerSeance frm = new SupprimerSeance();
                String add2=rs.getString("seance.ID");
                String sql= "UPDATE seance SET ETAT = '0' where (seance.ID='"+rs.getString("seance.ID")+"')";

            pst=con.prepareStatement(sql);
            pst.execute();
            
            }
            
            
            
            JOptionPane.showMessageDialog(this,"Suppression effectuée avec succès ","Note",JOptionPane.INFORMATION_MESSAGE);
            Supprimer.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void RéinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RéinitialiserActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_RéinitialiserActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupprimerSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupprimerSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupprimerSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupprimerSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupprimerSeance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JFormattedTextField Heure;
    private javax.swing.JTextField Nom;
    private javax.swing.JButton Réinitialiser;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
